In [1]:
from netCDF4 import Dataset

dataset= Dataset('Documentos/test_unos.nc', 'w', format='NETCDF4_CLASSIC')
print(dataset.data_model)

NETCDF4_CLASSIC


In [2]:
lat = dataset.createDimension('lat', 73)
lon = dataset.createDimension('lon', 144)
time = dataset.createDimension('time', None)
level = dataset.createDimension('level', 10)

In [3]:
for dimname in dataset.dimensions.keys():
    dim = dataset.dimensions[dimname]
    print(dimname, len(dim), dim.isunlimited())

lat 73 False
lon 144 False
time 0 True
level 10 False


In [4]:
import numpy as np

times = dataset.createVariable('time', np.float64, ('time',))
levels = dataset.createVariable('level', np.int32, ('level',))
latitudes = dataset.createVariable('latitude', np.float32,('lat',))
longitudes = dataset.createVariable('longitude', np.float32,('lon',)) 
temp = dataset.createVariable('temp', np.float32, ('time','level','lat','lon')) 


In [5]:
latitudes.units = 'degree_north'
longitudes.units = 'degree_north'
temp.units = 'K'
levels.units = 'hPa'
times.units= 'hours since 00:00:00'
times.calendar = 'gregorian'

In [6]:
lats = np.arange(-90,91,2.5)
lons = np.arange(-180,180,2.5)
latitudes[:] = lats
longitudes[:] = lons

In [8]:
print(temp.shape)

(0, 10, 73, 144)


In [10]:
times[0:10] = 1

In [29]:
print(temp.shape)
print(times[:])

(10, 10, 73, 144)
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [27]:
from numpy.random import uniform
nlats= len(dataset.dimensions['lat'])
nlons = len(dataset.dimensions['lon'])
temp[0:10,:,:] = uniform (size=(10,10,nlats,nlons))
print("before adding data", temp.shape)

before adding data (10, 10, 73, 144)


In [32]:
print(temp[2,:,:,:])

[[[0.53768027 0.7841922  0.91092885 ... 0.17580116 0.7739618  0.06302261]
  [0.49723867 0.10498758 0.59441185 ... 0.49289858 0.50820774 0.47441584]
  [0.43491483 0.01251916 0.08635291 ... 0.9613221  0.62813395 0.43174323]
  ...
  [0.2596742  0.7795311  0.86225003 ... 0.22031598 0.44883865 0.2003616 ]
  [0.9573855  0.4550296  0.6863394  ... 0.2972541  0.8627309  0.54603034]
  [0.5696496  0.59450084 0.02324376 ... 0.32209352 0.46980485 0.68392265]]

 [[0.1433918  0.88992864 0.5918446  ... 0.14114179 0.37973863 0.9944404 ]
  [0.7660012  0.5785562  0.22135527 ... 0.04474083 0.39232543 0.8744894 ]
  [0.17808034 0.6799964  0.78392905 ... 0.76936513 0.33487782 0.24293151]
  ...
  [0.5135768  0.93819106 0.05729207 ... 0.17050248 0.9938108  0.00943985]
  [0.5077463  0.8355003  0.6656979  ... 0.88233924 0.2522263  0.6620266 ]
  [0.8237317  0.34207648 0.09630984 ... 0.13342048 0.7728033  0.5994197 ]]

 [[0.03410514 0.9026939  0.63175577 ... 0.6377655  0.31941316 0.86029506]
  [0.68793184 0.391819